/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_Hd6kKCbPp",
    "aws_user_pools_web_client_id": "5g5eqgulo7pjnv0q8ethg1tcqp",
    "oauth": {}
};


export default awsmobile;
