/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_4k05ilMvr",
    "aws_user_pools_web_client_id": "2jjk1a32065eb0bvvfs92d8tof",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "ap-northeast-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "user",
            "region": "ap-northeast-2"
        }
    ]
};


export default awsmobile;
